"""Add document sharing, user education level, and attempt source tracking

Revision ID: 3295efca321d
Revises: 
Create Date: 2026-02-24 10:29:21.034343
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3295efca321d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'shared_with_user_id', name='uq_document_share')
    )
    op.add_column('attempts', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attempts', 'documents', ['document_id'], ['id'])
    op.add_column('documents', sa.Column('is_personal', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('documents', sa.Column('is_shared', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_documents_is_archived'), 'documents', ['is_archived'], unique=False)
    op.create_index(op.f('ix_documents_is_personal'), 'documents', ['is_personal'], unique=False)
    op.create_index(op.f('ix_documents_is_shared'), 'documents', ['is_shared'], unique=False)
    op.add_column('users', sa.Column('education_level', sa.Enum('P6', 'S3', 'S6', 'TTC', name='education_level_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'education_level')
    op.drop_index(op.f('ix_documents_is_shared'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_personal'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_archived'), table_name='documents')
    op.drop_column('documents', 'is_shared')
    op.drop_column('documents', 'is_personal')
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_column('attempts', 'document_id')
    op.drop_table('document_shares')
    # ### end Alembic commands ###
