"""Add document sharing, user education level, and attempt source tracking

Revision ID: 3295efca321d
Revises: 0_initial
Create Date: 2026-02-24 10:29:21.034343
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3295efca321d'
down_revision: Union[str, None] = '0_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # All changes for this migration are now part of the initial migration (0_initial):
    # - document_shares table
    # - document_id column on attempts
    # - is_personal, is_shared columns on documents  
    # - indexes on is_archived, is_personal, is_shared
    # - education_level column on users
    # 
    # This migration is now effectively a no-op
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'education_level')
    op.drop_index(op.f('ix_documents_is_shared'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_personal'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_archived'), table_name='documents')
    op.drop_column('documents', 'is_shared')
    op.drop_column('documents', 'is_personal')
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_column('attempts', 'document_id')
    op.drop_table('document_shares')
    # ### end Alembic commands ###
